# Generated by Django 3.2.6 on 2021-08-29 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chat',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Subjects.subject'),
        ),
    ]
