# Generated by Django 3.2.6 on 2021-08-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0002_auto_20210829_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='faculty_name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_name',
        ),
    ]
