# Generated by Django 3.2.6 on 2021-08-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0003_auto_20210829_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='period',
            field=models.CharField(default='', max_length=10),
        ),
    ]
