# Generated by Django 3.2.6 on 2021-08-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0004_chat_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
