# Generated by Django 3.2.6 on 2021-08-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0005_chat_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='course',
            field=models.CharField(default='', max_length=100),
        ),
    ]
