# Generated by Django 3.2.6 on 2021-08-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0008_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='mess_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
