# Generated by Django 3.2.6 on 2021-08-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0009_request_mess_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='added',
            field=models.BooleanField(default=False),
        ),
    ]
